//
//  Post.swift
//  Offsight-TH
//
//  Created by Vishal Singh on 04/02/21.
//

import Foundation

struct DummyAPIData: Codable {
    private(set) var posts: [Post]
    
    enum CodingKeys: String, CodingKey {
        case posts = "data"
    }
}

struct Post: Codable {
    
    private(set) var text: String? // string(length: 6-1000)
    private(set) var image: String? // string(url)
    private(set) var likes: Int? // number(init value: 0)
    private(set) var link: String? //string(url, length: 6-200)
    private(set) var tags: [String] // array(string)
    private(set) var publishDate: String? // string(autogenerated)
//    var owner: User// model(ref:User)
}
